import {
  IconType,
  SiActivision,
  SiAdobe,
  SiAirbnb,
  SiAmazon,
  SiAmazonwebservices,
  SiAnydesk,
  SiAol,
  SiApple,
  SiAppsignal,
  SiAppveyor,
  SiAppwrite,
  SiArduino,
  SiArtstation,
  SiAsana,
  SiAtlassian,
  SiAuth0,
  SiAutodesk,
  SiBankofamerica,
  SiBattledotnet,
  SiBetfair,
  SiBinance,
  SiBitbucket,
  SiBlockchaindotcom,
  SiBluesky,
  SiBuymeacoffee,
  SiCalendly,
  SiCanva,
  SiChessdotcom,
  SiCircle,
  SiClickup,
  SiCloud66,
  SiCloudflare,
  SiCloudways,
  SiCoinbase,
  SiCoinmarketcap,
  SiDigitalocean,
  SiDiscord,
  SiDocker,
  SiDropbox,
  SiEbay,
  SiElasticcloud,
  SiElement,
  SiEpicgames,
  SiEquinixmetal,
  SiEtsy,
  SiEvernote,
  SiExpo,
  SiFacebook,
  SiFacebookgaming,
  SiFaceit,
  SiFandom,
  SiFastly,
  SiFauna,
  SiFavro,
  SiFedex,
  SiFigma,
  SiFiverr,
  SiFreelancer,
  SiGamemaker,
  SiGithub,
  SiGitlab,
  SiGmail,
  SiGodaddy,
  SiGofundme,
  SiGogdotcom,
  SiGooglecloud,
  SiGoogledrive,
  SiGooglemeet,
  SiHeroku,
  SiHetzner,
  SiHostinger,
  SiHuawei,
  SiHuggingface,
  SiHumblebundle,
  SiIbmcloud,
  SiIcloud,
  SiInstagram,
  SiItchdotio,
  SiJetbrains,
  SiKick,
  SiKickstarter,
  SiKik,
  SiKofi,
  SiLichess,
  SiLinkedin,
  SiLogitech,
  SiMailgun,
  SiMastodon,
  SiMercadopago,
  SiMeta,
  SiMicrosoftazure,
  SiMicrosoftonedrive,
  SiMicrosoftoutlook,
  SiMinecraft,
  SiModrinth,
  SiMongodb,
  SiNetflix,
  SiNetlify,
  SiNexusmods,
  SiNgrok,
  SiNiconico,
  SiNintendo,
  SiNintendo3ds,
  SiNintendoswitch,
  SiNotion,
  SiNpm,
  SiNubank,
  SiNvidia,
  SiObsidian,
  SiOpenai,
  SiOpencollective,
  SiOracle,
  SiOrigin,
  SiOsu,
  SiOvh,
  SiPayoneer,
  SiPaypal,
  SiPinterest,
  SiPixiv,
  SiPlaystation,
  SiPlex,
  SiProton,
  SiProtonmail,
  SiPypi,
  SiRaspberrypi,
  SiRazer,
  SiReddit,
  SiRedis,
  SiRender,
  SiRiotgames,
  SiRoblox,
  SiRockstargames,
  SiSalesforce,
  SiScaleway,
  SiSentry,
  SiServerless,
  SiShortcut,
  SiSignal,
  SiSketch,
  SiSkype,
  SiSlack,
  SiSnapchat,
  SiSoundcloud,
  SiSquareenix,
  SiStarlingbank,
  SiSteam,
  SiStripe,
  SiSupabase,
  SiTelegram,
  SiTiktok,
  SiTrello,
  SiTumblr,
  SiTutanota,
  SiTwilio,
  SiTwitch,
  SiUber,
  SiUnity,
  SiUphold,
  SiVimeo,
  SiVk,
  SiVmware,
  SiVultr,
  SiWarnerbros,
  SiWetransfer,
  SiWorkplace,
  SiXbox,
  SiYoutube,
  SiZoho,
  SiZoom,
} from "@icons-pack/react-simple-icons";

type IconGroup = { [key in string]: IconType };

// Betting
export const Betting: IconGroup = {
  Betfair: SiBetfair,
};

// Cloud Storage
export const Cloud: IconGroup = {
  "Apple iCloud": SiIcloud,
  Dropbox: SiDropbox,
  Evernote: SiEvernote,
  Obsidian: SiObsidian,
  OneDrive: SiMicrosoftonedrive,
};

// Communication
export const Communication: IconGroup = {
  Bluesky: SiBluesky,
  Calendly: SiCalendly,
  Discord: SiDiscord,
  Element: SiElement,
  Facebook: SiFacebook,
  Fandom: SiFandom,
  Favro: SiFavro,
  "Google Meet": SiGooglemeet,
  Instagram: SiInstagram,
  Kik: SiKik,
  LinkedIn: SiLinkedin,
  Mailgun: SiMailgun,
  Mastodon: SiMastodon,
  Reddit: SiReddit,
  Salesforce: SiSalesforce,
  Signal: SiSignal,
  Skype: SiSkype,
  Slack: SiSlack,
  Snapchat: SiSnapchat,
  Telegram: SiTelegram,
  TikTok: SiTiktok,
  Tumblr: SiTumblr,
  VK: SiVk,
  Workplace: SiWorkplace,
  Zoho: SiZoho,
  Zoom: SiZoom,
};

// Creativity
export const Creativity: IconGroup = {
  Adobe: SiAdobe,
  ArtStation: SiArtstation,
  Autodesk: SiAutodesk,
  Canva: SiCanva,
  Figma: SiFigma,
  Notion: SiNotion,
  Pinteres: SiPinterest,
  Pixiv: SiPixiv,
  Sketch: SiSketch,
  WeTransfer: SiWetransfer,
};

// Email
export const Email: IconGroup = {
  "Aol Mail": SiAol,
  Gmail: SiGmail,
  Outlook: SiMicrosoftoutlook,
  "Proton Mail": SiProtonmail,
  Tuta: SiTutanota,
};

// Entertainment
export const Entertainment: IconGroup = {
  Kick: SiKick,
  Netflix: SiNetflix,
  Niconico: SiNiconico,
  Plex: SiPlex,
  SoundCloud: SiSoundcloud,
  Twitch: SiTwitch,
  Vimeo: SiVimeo,
  YouTube: SiYoutube,
};

// Finance
export const Finance: IconGroup = {
  "Bank of America": SiBankofamerica,
  Binance: SiBinance,
  "Blockchain.com": SiBlockchaindotcom,
  "Buy Me a Coffee": SiBuymeacoffee,
  Circle: SiCircle,
  Coinbase: SiCoinbase,
  CoinMarketCap: SiCoinmarketcap,
  GoFundMe: SiGofundme,
  Kickstarter: SiKickstarter,
  "Ko-fi": SiKofi,
  "Mercado Pago": SiMercadopago,
  "Nu bank": SiNubank,
  "Open Collective": SiOpencollective,
  PayPal: SiPaypal,
  Payoneer: SiPayoneer,
  Stripe: SiStripe,
  "Starling bank": SiStarlingbank,
  Uphold: SiUphold,
};

// Gaming
export const Gaming: IconGroup = {
  Activision: SiActivision,
  "Battle.net": SiBattledotnet,
  "Chess.com": SiChessdotcom,
  "Epic Games": SiEpicgames,
  FaceIT: SiFaceit,
  "Facebook Gaming": SiFacebookgaming,
  GameMaker: SiGamemaker,
  "GOG.com": SiGogdotcom,
  "Humble Bundle": SiHumblebundle,
  "itch.io": SiItchdotio,
  Lichess: SiLichess,
  Meta: SiMeta,
  Minecraft: SiMinecraft,
  Modrinth: SiModrinth,
  "Nexus Mods": SiNexusmods,
  Nintendo: SiNintendo,
  "Nintendo Switch": SiNintendoswitch,
  "Nintendo 3DS": SiNintendo3ds,
  Nvidia: SiNvidia,
  Origin: SiOrigin,
  "osu!": SiOsu,
  Playstation: SiPlaystation,
  Razer: SiRazer,
  "Riot Games": SiRiotgames,
  Roblox: SiRoblox,
  Rockstar: SiRockstargames,
  "Square Enix": SiSquareenix,
  Steam: SiSteam,
  "Warner Bros": SiWarnerbros,
  Xbox: SiXbox,
};

// Life
export const Life: IconGroup = {
  Airbnb: SiAirbnb,
  Amazon: SiAmazon,
  eBay: SiEbay,
  Etsy: SiEtsy,
  FedEx: SiFedex,
  Fiverr: SiFiverr,
  Freelancer: SiFreelancer,
  Lego: SiLogitech,
  Uber: SiUber,
};

// Productivity
export const Productivity: IconGroup = {
  Asana: SiAsana,
  ClickUp: SiClickup,
  Shortcut: SiShortcut,
  Trello: SiTrello,
};

// Technology
export const Technology: IconGroup = {
  Apple: SiApple,
  Anydesk: SiAnydesk,
  Arduino: SiArduino,
  Atlassian: SiAtlassian,
  AWS: SiAmazonwebservices,
  AppSignal: SiAppsignal,
  AppVeyor: SiAppveyor,
  Appwrite: SiAppwrite,
  Auth0: SiAuth0,
  Bitbucket: SiBitbucket,
  "Cloud 66": SiCloud66,
  Cloudflare: SiCloudflare,
  Cloudways: SiCloudways,
  DigitalOcean: SiDigitalocean,
  Docker: SiDocker,
  "Elastic Cloud": SiElasticcloud,
  "Equinix Metal": SiEquinixmetal,
  Expo: SiExpo,
  Fastly: SiFastly,
  Fauna: SiFauna,
  GitHub: SiGithub,
  GitLab: SiGitlab,
  GoDaddy: SiGodaddy,
  "Google Cloud": SiGooglecloud,
  Heroku: SiHeroku,
  Hetzner: SiHetzner,
  Hostinger: SiHostinger,
  "Huawei Cloud": SiHuawei,
  HuggingFace: SiHuggingface,
  "Google Drive": SiGoogledrive,
  "IBM Cloud": SiIbmcloud,
  JetBrains: SiJetbrains,
  "Microsoft Azure": SiMicrosoftazure,
  MongoDB: SiMongodb,
  Netlify: SiNetlify,
  ngrok: SiNgrok,
  npm: SiNpm,
  OpenAI: SiOpenai,
  Oracle: SiOracle,
  OVH: SiOvh,
  Proton: SiProton,
  PyPI: SiPypi,
  Redis: SiRedis,
  Render: SiRender,
  "Raspberry PI": SiRaspberrypi,
  Scaleway: SiScaleway,
  Sentry: SiSentry,
  Serverless: SiServerless,
  Supabase: SiSupabase,
  Twilio: SiTwilio,
  VMware: SiVmware,
  Vultr: SiVultr,
  Unity: SiUnity,
};

export const Icons: { [key in string]: IconType } = {
  ...Betting,
  ...Cloud,
  ...Communication,
  ...Creativity,
  ...Email,
  ...Entertainment,
  ...Finance,
  ...Gaming,
  ...Life,
  ...Productivity,
  ...Technology,
};

export type IconWithMeta = { icon: IconType; name: string };

export function findIcons(query: string): IconWithMeta[] {
  const results: IconWithMeta[] = [];
  for (const [name, icon] of Object.entries(Icons)) {
    if (name.toLowerCase().includes(query.toLowerCase())) {
      results.push({ icon, name });
    }
  }
  return results.sort((a, b) => a.name.localeCompare(b.name));
}

export function getIcon(name: string): IconType | undefined {
  if (!name || !name.trim().length) return undefined;
  return Icons[name];
}
